services:
  aipi:
    image: ghcr.io/flyljx/hm:latest
    container_name: aipi-go
    restart: unless-stopped
    env_file:
      - .env
    environment:
      TZ: Asia/Shanghai
    ports:
      - "6985:3001"
    volumes:
      - ./logs:/app/logs
