package settings

type Settings map[string]any

var Defaults = Settings{
	"siteName":                          "AIπ",
	"logoText":                          "AIπ",
	"creditName":                        "积分",
	"frontendUrl":                       "http://localhost:5173",
	"backendUrl":                        "http://localhost:3001",
	"announcementEnabled":               true,
	"announcementTitle":                 "系统公告",
	"announcementContent":               "欢迎使用 AIπ 生图工作台，充值后即可开始创作。",
	"supportEnabled":                    true,
	"supportTitle":                      "联系客服",
	"supportDescription":                "遇到充值、生成或账号问题，可以通过下面方式联系管理员。",
	"supportWechat":                     "",
	"supportQq":                         "",
	"supportEmail":                      "",
	"supportUrl":                        "",
	"supportQrCodeUrl":                  "",
	"rechargeEnabled":                   true,
	"rechargeRate":                      float64(1),
	"rechargeMinAmount":                 float64(1),
	"rechargePresets":                   "10,30,50,100",
	"checkinEnabled":                    true,
	"checkinRewards":                    "0.1,0.2,0.3,0.5,0.8,1",
	"inviteEnabled":                     true,
	"inviteRewardCredits":               float64(1),
	"taskTimeoutMinutes":                float64(3),
	"streamGenerationEnabled":           false,
	"promptModerationEnabled":           true,
	"promptModerationAdultKeywords":     "裸体\n裸露\n色情\n黄图\n成人\n性爱\n性交\n做爱\n露点\n私处\n乳头\n生殖器\n强奸\n未成年色情",
	"promptModerationPoliticalKeywords": "习近平\n毛泽东\n共产党\n中共\n台湾独立\n台独\n港独\n藏独\n疆独\n六四\n法轮功\n政治宣传\n推翻政府",
	"promptModerationRejectMessage":     "提示词包含不支持生成的敏感内容，请修改后再试。",
	"alipayAppId":                       "",
	"alipayPrivateKey":                  "",
	"alipayPublicKey":                   "",
	"alipayGateway":                     "https://openapi.alipay.com/gateway.do",
	"registerMode":                      "open",
	"registerRewardCredits":             float64(0),
	"emailEnabled":                      false,
	"emailHost":                         "",
	"emailPort":                         float64(465),
	"emailSecure":                       true,
	"emailUser":                         "",
	"emailPassword":                     "",
	"emailFromName":                     "AIπ",
	"emailFromAddress":                  "",
	"registerEmailVerification":         false,
	"accountPoolEndpoint":               "https://free-api.yccc.me/api/accounts",
	"accountPoolApiKey":                 "",
	"accountPoolAuthHeader":             "Authorization",
	"barkEnabled":                       false,
	"barkServerUrl":                     "https://api.day.app",
	"barkDeviceKey":                     "",
	"barkTitlePrefix":                   "AIπ",
	"barkSound":                         "",
	"barkNotifyGenerationFailure":       true,
	"barkNotifyTaskTimeout":             true,
	"barkNotifyProviderFailure":         true,
}

var publicKeys = map[string]bool{
	"siteName":                  true,
	"logoText":                  true,
	"creditName":                true,
	"frontendUrl":               true,
	"backendUrl":                true,
	"announcementEnabled":       true,
	"announcementTitle":         true,
	"announcementContent":       true,
	"supportEnabled":            true,
	"supportTitle":              true,
	"supportDescription":        true,
	"supportWechat":             true,
	"supportQq":                 true,
	"supportEmail":              true,
	"supportUrl":                true,
	"supportQrCodeUrl":          true,
	"rechargeEnabled":           true,
	"rechargeRate":              true,
	"rechargeMinAmount":         true,
	"rechargePresets":           true,
	"checkinEnabled":            true,
	"checkinRewards":            true,
	"inviteEnabled":             true,
	"inviteRewardCredits":       true,
	"taskTimeoutMinutes":        true,
	"streamGenerationEnabled":   true,
	"registerMode":              true,
	"registerRewardCredits":     true,
	"registerEmailVerification": true,
}

func Public(settings Settings) Settings {
	result := Settings{}
	for key, value := range settings {
		if publicKeys[key] {
			result[key] = value
		}
	}
	return result
}
